### ISSUE TITLE
let optional columns be optional

### ISSUE THREAD

**Issue by sbailey** [cballand/desibest#4]
parsezbest will refuse to calculate statistics if the zbest file is missing the BRICKNAME and SUBTYPE columns, even though it doesn't use them.  It would be better to just print a warning telling the user to fix that, but proceed with the calculations anyway.

Similarly, if EXTNAME='ZBEST' doesn't exist, print a warning and proceed with trying to use whatever is in HDU 1.

**Comment by cballand** [comment]
Done.
